version: "3"
services:
  front:
    container_name: earth_front
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/html:/usr/share/nginx/html:ro"

  master:
    container_name: earth_master
    image: arjones/pyspark:2.4.5
    restart: always
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      MASTER: spark://master:7077
      SPARK_NO_DAEMONIZE: 1
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  worker1:
    container_name: earth_worker1
    image: arjones/pyspark:2.4.5
    restart: always
    command:
      [
        "/opt/spark/sbin/start-slave.sh",
        "spark://master:7077",
        "--memory",
        "512m",
        "--cores",
        "2",
      ]
    environment:
      MASTER: spark://master:7077
      SPARK_NO_DAEMONIZE: 1
    depends_on:
      - master
    ports:
      - 4041:4040
      - "6066"
      - "7077"
      - 8081:8080
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  worker2:
    container_name: earth_worker2
    image: arjones/pyspark:2.4.5
    restart: always
    command:
      [
        "/opt/spark/sbin/start-slave.sh",
        "spark://master:7077",
        "--memory",
        "512m",
        "--cores",
        "2",
      ]
    environment:
      MASTER: spark://master:7077
      SPARK_NO_DAEMONIZE: 1
    depends_on:
      - master
    ports:
      - 4042:4040
      - "6066"
      - "7077"
      - 8082:8080
    volumes:
      - ./code:/app
      - ./dataset:/dataset

  jupyter:
    container_name: earth_jupyter
    image: arjones/pyspark:2.4.5
    restart: always
    environment:
      MASTER: spark://master:7077
    depends_on:
      - master
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebook:/notebook
      - ./dataset:/dataset
      - ./code:/app

  postgres:
    container_name: earth_postgres
    image: postgres:11
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: agricultura
      POSTGRES_USER: agricultura
      POSTGRES_PASSWORD: p4ssW0rdP4r4Agr1cultur4
    ports:
      - "5432:5432"

  redis:
    container_name: earth_redis
    image: redis
    restart: always

  superset:
    container_name: earth_superset
    image: amancevice/superset
    restart: always
    depends_on:
      - redis
      - postgres
    environment:
      SUPERSET_HOME: /etc/superset
    ports:
      - "8088:8088"
    volumes:
      - ./superset/conf/superset_config.py:/etc/superset/superset_config.py
      - ./superset/dashboards:/home/superset/dashboards
      - superset:/var/lib/superset

volumes:
  postgres-data:
  superset:
